import type { Metadata } from 'next'
import '@/styles/globals.css'
import Header from '@/components/header/Header'
import Footer from '@/components/footer/Footer'

export const metadata: Metadata = {
    title: 'Cabinet Cap Patrimoine',
    description: 'Generated by create next app',
    icons: [
        {
          rel: 'icon',
          type: 'image/png',
          sizes: '32x32',
          url: '/public/favicon-32x32.png',
        },
        {
          rel: 'icon',
          type: 'image/png',
          sizes: '16x16',
          url: '/public/favicon-16x16.png',
        },
        {
          rel: 'apple-touch-icon',
          sizes: '180x180',
          url: '/public/apple-touch-icon.png',
        },
      ],
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="fr">
            <body>
                <Header />
                {children}
                <Footer />
            </body>
        </html>
    )
}
